name = "notes"
type = "webpack"
webpack_config = "webpack.config.js"

[env.production]
route = "*fstn.dev/*"
kv_namespaces = [
  { binding = "CACHED_RESPONSE", id = "fca8dff41e4f448a9ddbb6320b999b1f", preview_id = "fc66373a36544434b19c88c22590ebe7" }
]
